In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
matches_cleaned = pd.read_csv("matches_cleaned.csv")
matches_cleaned

       match_id  duration  radiant_win
0             0      2375         True
1             1      2582        False
2             2      2716        False
3             3      3085        False
4             4      1887         True
...         ...       ...          ...
49995     49995      3025         True
49996     49996      1451         True
49997     49997      2672         True
49998     49998      2211         True
49999     49999      2788        False

[50000 rows x 3 columns]

In [ ]:
players_cleaned = pd.read_csv("players_cleaned.csv")

In [7]:
players_cleaned = players_cleaned[["match_id", "player_slot", "hero_id"]]

In [10]:
players_cleaned

        match_id  player_slot  hero_id
0              0            0       86
1              0            1       51
2              0            2       83
3              0            3       11
4              0            4       67
...          ...          ...      ...
499995     49999          128      100
499996     49999          129        9
499997     49999          130       90
499998     49999          131       73
499999     49999          132       53

[500000 rows x 3 columns]

In [8]:
#players_cleaned.to_csv("players_cleaned.csv", index=False)

In [13]:
players_cleaned["player_slot"].value_counts()

player_slot
0      50000
1      50000
2      50000
3      50000
4      50000
128    50000
129    50000
130    50000
131    50000
132    50000
Name: count, dtype: int64

In [11]:
players_aggregated = players_cleaned.pivot(
    index="match_id",
    columns="player_slot",
    values="hero_id"
).reset_index()

In [12]:
players_aggregated

player_slot  match_id    0    1    2   3   4  128  129  130  131  132
0                   0   86   51   83  11  67  106  102   46    7   73
1                   1    7   82   71  39  21   73   22    5   67  106
2                   2   51  109    9  41  27   38    7   10   12   85
3                   3   50   44   32  26  39   78   19   31   40   47
4                   4    8   39   55  87  69  101  100   22   67   21
...               ...  ...  ...  ...  ..  ..  ...  ...  ...  ...  ...
49995           49995   73   86   21  20  14   32    7  109   35  112
49996           49996   93   74  100  32  85   36    1  112   60   71
49997           49997  100   68   75  39  44   28  102   21    9   23
49998           49998   56   50    2  72  30   46    7   29   44    3
49999           49999   94   19   68  35  21  100    9   90   73   53

[50000 rows x 11 columns]

In [15]:
players_aggregated = players_aggregated.rename(columns={
    0: "Radiant_1",
    1: "Radiant_2",
    2: "Radiant_3",
    3: "Radiant_4",
    4: "Radiant_5",
    128: "Dire_1",
    129: "Dire_2",
    130: "Dire_3",
    131: "Dire_4",
    132: "Dire_5"
})

In [16]:
players_aggregated

player_slot,match_id,Radiant_1,Radiant_2,Radiant_3,Radiant_4,Radiant_5,Dire_1,Dire_2,Dire_3,Dire_4,Dire_5
0,0,86,51,83,11,67,106,102,46,7,73
1,1,7,82,71,39,21,73,22,5,67,106
2,2,51,109,9,41,27,38,7,10,12,85
3,3,50,44,32,26,39,78,19,31,40,47
4,4,8,39,55,87,69,101,100,22,67,21
...,...,...,...,...,...,...,...,...,...,...,...
49995,49995,73,86,21,20,14,32,7,109,35,112
49996,49996,93,74,100,32,85,36,1,112,60,71
49997,49997,100,68,75,39,44,28,102,21,9,23
49998,49998,56,50,2,72,30,46,7,29,44,3
49999,49999,94,19,68,35,21,100,9,90,73,53

In [17]:
#players_aggregated.to_csv("players_aggregated.csv", index=False)

In [18]:
heroes_cleaned = pd.read_csv("heroes_cleaned.csv")
heroes_cleaned

     hero_id  localized_name
0          1       Anti-Mage
1          2             Axe
2          3            Bane
3          4     Bloodseeker
4          5  Crystal Maiden
..       ...             ...
107      109     Terrorblade
108      110         Phoenix
109      111          Oracle
110      112   Winter Wyvern
111      113      Arc Warden

[112 rows x 2 columns]

In [19]:
final_dataset = players_aggregated.merge(
    matches_cleaned[["match_id", "radiant_win"]],
    on="match_id",
    how="inner"
)

In [20]:
#final_dataset.to_csv("final_dataset.csv", index=False)

In [21]:
final_dataset

,match_id,Radiant_1,Radiant_2,Radiant_3,Radiant_4,Radiant_5,Dire_1,Dire_2,Dire_3,Dire_4,Dire_5,radiant_win
0,0,86,51,83,11,67,106,102,46,7,73,True
1,1,7,82,71,39,21,73,22,5,67,106,False
2,2,51,109,9,41,27,38,7,10,12,85,False
3,3,50,44,32,26,39,78,19,31,40,47,False
4,4,8,39,55,87,69,101,100,22,67,21,True
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49995,73,86,21,20,14,32,7,109,35,112,True
49996,49996,93,74,100,32,85,36,1,112,60,71,True
49997,49997,100,68,75,39,44,28,102,21,9,23,True
49998,49998,56,50,2,72,30,46,7,29,44,3,True
49999,49999,94,19,68,35,21,100,9,90,73,53,False

In [24]:
final_dataset.columns

Index(['match_id', 'Radiant_1', 'Radiant_2', 'Radiant_3', 'Radiant_4',
       'Radiant_5', 'Dire_1', 'Dire_2', 'Dire_3', 'Dire_4', 'Dire_5',
       'radiant_win'],
      dtype='str')